### ISSUE TITLE
Have an explicit mutatingwebhookconfiguration resource in the dlf.yaml deployment.

### ISSUE THREAD

**Issue by Tomcli** [IBM/dataset-lifecycle-framework#51]
We want to have the mutatingwebhookconfiguration explicitly defined in the dlf.yaml deployment. So that we can also delete the webhook using the same dlf.yaml

**Comment by YiannisGkoufas** [comment]
some progress on this one @Tomcli, unfortunately at this point we cannot bundle the webhook configuration in the dlf.yaml since it requires the CA_BUNDLE value to be set. that's why it's populated within the generate-keys pod.
as a workaround I added just the definition ( https://github.com/IBM/dataset-lifecycle-framework/blob/master/src/generate-keys/webhook-definition.yaml ) which you can use it to delete the resource and also added the capability to generate the keys from host, by using the script https://github.com/IBM/dataset-lifecycle-framework/blob/master/src/generate-keys/script.sh
in the long term I am looking for a solution based on cert-manager ( https://cert-manager.io/docs/installation/kubernetes/ )

**Comment by Tomcli** [comment]
thanks @YiannisGkoufas. Quick question, if we deploy the webhook without `CA_BUNDLE`, will the controller overwrite the webhook with the correct `CA_BUNDLE` value?

We are using kustomize `kubectl -k` to deploy all of this without script. That's why we want the webhook to be explicit.

**Comment by Tomcli** [comment]
Another way could be, if the controller deployment is deleted, the controller's finalizer logic should delete the webhook as part of terminating the pod.

**Comment by YiannisGkoufas** [comment]
> thanks @YiannisGkoufas. Quick question, if we deploy the webhook without `CA_BUNDLE`, will the controller overwrite the webhook with the correct `CA_BUNDLE` value?

That's a good point, it actually does apply so in theory it should work. Let me test it out and get back to you

> We are using kustomize `kubectl -k` to deploy all of this without script. That's why we want the webhook to be explicit.

I wanted to migrate everything to kustomize, but the biggest problem I faced was about customizing `/var/lib/kubelet` path

**Comment by YiannisGkoufas** [comment]
Hi @Tomcli with the latest push I am creating the mutating webhook and the secrets as an init container of dataset operator. Also I included the yamls (which would be updated by the init container) so we have all the resources in dlf.yaml
Let me know if this works for you so I can close this one.

**Comment by Tomcli** [comment]
Thanks @YiannisGkoufas. I think we pulled the latest code a while ago and didn't see any problem, I did a delete and redeploy and it also works.
We can close this issue now.
